export const notificationsTypes = {
    FETCH_NOTIFICATIONS_REQUEST: "[NOTIFICATIONS] FETCH REQUEST",
    FETCH_NOTIFICATIONS_FINISH: "[NOTIFICATIONS] FETCH FINISH",
    FETCH_NOTIFICATIONS_FAIL: "[NOTIFICATIONS] FETCH FAIL",
  };