export const authTypes = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FINISH: "LOGIN_FINISH",
  LOGIN_FAIL: "LOGIN_FAIL",
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_FINISH: "SIGNUP_FINISH",
  SIGNUP_FAIL: "SIGNUP_FAIL",
  LOGOUT_USER: "LOGOUT_USER",
};
