export const guidanceTypes = {
  BOOK_SESSION_REQUEST: "BOOK_SESSION_REQUEST",
  BOOK_SESSION_FINISH: "BOOK_SESSION_FINISH",
  BOOK_SESSION_FAIL: "BOOK_SESSION_FAIL",
  GUIDANCE_FILTER_REQUEST: "GUIDANCE_FILTER_REQUEST",
  GUIDANCE_FILTER_FINISH: "GUIDANCE_FILTER_FINISH",
  GUIDANCE_FILTER_FAIL: "GUIDANCE_FILTER_FAIL"
};
