export const coursesTypes = {
  COURSES_REQUEST: "COURSES_REQUEST",
  COURSES_FINISH: "COURSES_FINISH",
  COURSES_FAIL: "COURSES_FAIL",
  TESTS_REQUEST: "TESTS_REQUEST",
  TESTS_FINISH: "TESTS_FINISH",
  TESTS_FAIL: "TESTS_FAIL",
  COURSE_REQUEST: "COURSE_REQUEST",
  COURSE_FINISH: "COURSE_FINISH",
  COURSE_FAIL: "COURSE_FAIL",
  ACCORDIAN_LIST_REQUEST : "ACCORDIAN_LIST_REQUEST",
  ACCORDIAN_LIST_FINISH : "ACCORDIAN_LIST_FINISH",
  ACCORDIAN_LIST_FAIL : "ACCORDIAN_LIST_FAIL"
};
