export const coursesTypes = {
  COURSES_REQUEST: "COURSES_REQUEST",
  COURSES_FINISH: "COURSES_FINISH",
  COURSES_FAIL: "COURSES_FAIL",
  COURSE_REQUEST: "COURSE_REQUEST",
  COURSE_FINISH: "COURSE_FINISH",
  COURSE_FAIL: "COURSE_FAIL"
};
